apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: pod-runner
  name: my-docker-pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: docker
      image: docker:20.10.12-alpine3.15
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
      resources:  # limits the resources your build contaienr
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock