version: '3.9'
services:
  app_instance:
    build: .
    image: weather_app
    networks:
      - app
      - db
    env_file:
      - ./env/app.env
      - ./env/flask.env
    depends_on:
      db_instance:
        condition: service_healthy
    ports:
      - "5000:5000"

  db_instance:
    image: mysql
    networks:
      - db
    env_file:
      - ./env/db.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "db_instance"]
      timeout: 20s
      retries: 10

networks:
  app:
  db: