apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-deployment
  labels:
    app: weatherapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: ___K8S_IMG___
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: weatherapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
