apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-db
    #   role: primary
      tier: backend
  template:
    metadata:
      labels:
        app: weather-db
        # role: primary
        tier: backend
    spec:
      containers:
      - name: mysql
        image: mysql
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: weather-db-secret
              key: dbname
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: weather-db-secret
              key: dbuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: weather-db-secret
              key: userpass
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: weather-db-secret
              key: rootpass