apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   flux.weave.works/automated: "true"
  name: weather-app
spec:
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: ___K8S_IMG___
          # image: mzoorg/weatherapp
          imagePullPolicy: IfNotPresent
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          #   successThreshold: 1
          #   timeoutSeconds: 1
          # readinessProbe:
          #   failureThreshold: 1
          #   httpGet:
          #     path: /
          #     port: 8080
          #     scheme: HTTP
          ports:
          - containerPort: 5000
            name: http
          env:
          - name: MYSQL_HOST
            value: 'weatherdb'
          - name: EXPORTER_PORT
            value: '5099'
          - name: MYSQL_DB
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: dbname
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: dbuser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: userpass
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi