apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
        - name: weather-app
          image: ___K8S_IMG___
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000
            name: http
          - containerPort: 5099
            name: prom
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 1500m
              memory: 1500Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
          volumeMounts:
          - name: db_models
            mountPath: /app/migrations
          env:          
          - name: EXPORTER_PORT
            value: '5099'
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: weatherdb
          - name: MYSQL_DB
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: dbname
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: dbuser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: weather-app-secret
                key: userpass
      volumes:
        - name: db_models
          persistentVolumeClaim:
            claimName: migrations-pvc