---
apiVersion: v1
kind: Service
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: weather-app